name = "php-library"
title = "PHP Library Manual"
eol = true

intersphinx = ["https://www.mongodb.com/docs/manual/objects.inv"]

toc_landing_pages = [
    "/reference/class/MongoDBClient",
    "/reference/class/MongoDBCollection",
    "/reference/class/MongoDBDatabase",
    "/reference/class/MongoDBGridFSBucket",
    "/reference/result-classes",
    "/reference/write-result-classes"
]

[substitutions]
php-library = "MongoDB PHP Library"

[[banners]]
targets = ["*"]
variant = "info"
value = """\
    This version of the documentation is archived and no longer supported. View the `current documentation <https://www.mongodb.com/docs/php-library/current/>`__ to learn how to `upgrade your version of the {+php-library+} <https://www.mongodb.com/docs/php-library/current/upgrade/>`__.\
    """
