name = "php-library"
title = "PHP Library Manual"

intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/drivers/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv",
]

toc_landing_pages = [
    "/reference/class/MongoDBClient",
    "/reference/class/MongoDBCollection",
    "/reference/class/MongoDBDatabase",
    "/reference/class/MongoDBGridFSBucket",
    "/reference/class/MongoDBBulkWriteResult",
    "/reference/class/MongoDBDeleteResult",
    "/reference/class/MongoDBInsertManyResult",
    "/reference/class/MongoDBUpdateResult",
    "/reference/class/MongoDBChangeStream",
    "/reference/class/MongoDBMapReduceResult",
    "/reference/class/MongoDBModelCollectionInfo",
    "/reference/class/MongoDBModelDatabaseInfo",
    "/reference/class/MongoDBModelIndexInfo",
    "/get-started",
    "/connect",
    "/databases-collections",
    "/write",
    "/indexes",
    "/security",
    "/data-formats"
]

sharedinclude_root =  "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[substitutions]
php-library = "MongoDB PHP Library"

[constants]
php-library = "MongoDB PHP Library"
driver-short = "PHP library"
extension-short = "PHP extension"
mdb-server = "MongoDB Server"
stable-api = "Stable API"
library-short = "PHP library"
api = "https://www.mongodb.com/docs/php-library/current/reference"
php-manual = "https://www.php.net/manual/en"
