git:
  repo: mongodb/docs-php-library
  remote:
    upstream: 'mongodb/docs-php-library'
    tools: 'mongodb/docs-tools'
project:
  name: 'php-library'
  tag: 'php-library'
  url: 'http://docs.mongodb.com/php-library'
  title: "PHP Library Manual"
  branched: true
version:
  release: '1.6'
  branch: 'master'
system:
  runstate:
    serial_sphinx: publish
  files:
    - 'intersphinx.yaml'
    - 'integration.yaml'
    - 'sphinx_local.yaml'
    - 'push.yaml'
    - htaccess: ['htaccess.yaml']
assets:
  - branch: master
    path: build/docs-tools
    repository: https://github.com/mongodb/docs-tools.git
paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
  images: 'source/images'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
...
