name: add-redirects
on:
  pull_request_target:
jobs:
  get-redirects:
    name: Get Redirects for Modified Files
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - name: Get modified files
        id: changed-files
        # pin to a specific commit to ensure stability
        uses: tj-actions/changed-files@c65cd883420fd2eb864698a825fc4162dd94482c
        with:
          files: source/**
          include_all_old_new_renamed_files: true
      - name: Parse renamed files
        id: renamed-files
        if: steps.changed-files.outputs.renamed_files_count > 0
        env:
          RENAMED_FILES: ${{ steps.changed-files.outputs.all_old_new_renamed_files }}
        run: |
          renamed_redirects=""
          for file in $RENAMED_FILES; do
            if (grep -s "source/"  <<< "$file") && 
                (grep -s "\.txt$" <<< "$file"); then
              old=$(echo "$file" | cut -d',' -f1)
              old="${old#source}"
              old="${old%.txt}"
              new=$(echo "$file" | cut -d',' -f2)
              new="${new#source}"
              new="${new%.txt}"
              #single quotes = ${var} rendered literally; double quotes = $var interpreted
              renamed_redirects+='<li>[&lt;v&gt;-*]: ${prefix}/${version}'"$old"'/ -> ${base}/${version}'"$new"'/</li>'
            fi
          done
          echo "redirects=${renamed_redirects}" >> "$GITHUB_OUTPUT"
      - name: Parse deleted files
        id: deleted-files
        if: steps.changed-files.outputs.deleted_files_count > 0
        env:
          DELETED_FILES: ${{ steps.changed-files.outputs.deleted_files }}
        run: |
          deleted_redirects=""
          for file in $DELETED_FILES; do
            old=$(echo "$file" | cut -d',' -f1)
            old="${old#source}"
            old="${old%.txt}"
            deleted_redirects+='<li>[&lt;v&gt;-*]: ${prefix}/${version}'"$old"'/ -> ${base}/${version}/</li>'
          done
          echo "redirects=${deleted_redirects}" >> "$GITHUB_OUTPUT"
      - name: Update the PR Description
        uses: MongoCaleb/pr-description-action@master
        with:
          regex: "<!-- start redirects -->.*<!-- end redirects -->"
          appendContentOnMatchOnly: true
          regexFlags: is
          content: "<!-- start redirects -->\n- [ ] Did you add redirects?\n *Suggested redirects for moved/deleted files (replace &lt;v&gt; with earliest backport target version):*\n${{ steps.renamed-files.outputs.redirects }}${{ steps.deleted-files.outputs.redirects }}\n<!-- end redirects -->"
          token: ${{ secrets.GITHUB_TOKEN }}