name: Verify Redirects

on:
  pull_request_target:

jobs:
  verify-redirects:
    name: Verifying Redirects
    runs-on: ubuntu-latest
    env:
      REDIRECTS_FILE: "config/redirects"
    permissions:
      pull-requests: write
    steps:
      - name: Check Out Base Branch
        uses: actions/checkout@v4

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@c65cd883420fd2eb864698a825fc4162dd94482c
        with:
          include_all_old_new_renamed_files: true

      - name: Find Missing Redirects for Renamed Files
        id: renamed-files
        if: steps.changed-files.outputs.renamed_files_count > 0
        env:
          RENAMED_FILES: ${{ steps.changed-files.outputs.all_old_new_renamed_files }}
        run: |
          renamed_redirects=()
          for file in $RENAMED_FILES; do

            # only run for .txt files
            if [[ ! "$file" == *.txt ]]; then
              continue
            fi

            # format old and new URLs
            old=$(echo "$file" | cut -d',' -f1)
            old="${old#source}"
            old="${old%.txt}"
            new=$(echo "$file" | cut -d',' -f2)
            new="${new#source}"
            new="${new%.txt}"
            
            # single quotes = ${var} rendered literally; double quotes = $var interpreted
            renamed_redirect='${prefix}/${version}'"$old"'/ -> ${base}/${version}'"$new"'/'

            # if redirect not already in file, add to array to add to PR description
            if ! grep -q "$renamed_redirect" $REDIRECTS_FILE; then
              renamed_redirects+=("$renamed_redirect")
            fi
          done
          echo "redirects=${renamed_redirects}" >> "$GITHUB_OUTPUT"

      - name: Find Missing Redirects for Deleted Files
        id: deleted-files
        if: steps.changed-files.outputs.deleted_files_count > 0
        env:
          DELETED_FILES: ${{ steps.changed-files.outputs.deleted_files }}
        run: |
          deleted_redirects=()
          for file in $DELETED_FILES; do

            # only run for .txt files
            if [[ ! "$file" == *.txt ]]; then
              continue
            fi
            
            # format old URL
            old=$(echo "$file" | cut -d',' -f1)
            old="${old#source}"
            old="${old%.txt}"
            
            # single quotes = ${var} rendered literally; double quotes = $var interpreted
            deleted_redirect='${prefix}/${version}'"$old"'/ -> ${base}/${version}/'
                       
            # if redirect not already in file, add to array to add to PR description
            if ! grep -q "$deleted_redirect" $REDIRECTS_FILE; then  
              deleted_redirects+=("$deleted_redirect")
            fi

          done
          echo "redirects=${deleted_redirects}" >> "$GITHUB_OUTPUT"

      - name: Build Redirect HTML
        id: build-redirect-html
        env:
          RENAMED_REDIRECTS: ${{ steps.renamed-files.outputs.redirects }}
          DELETED_REDIRECTS: ${{ steps.deleted-files.outputs.redirects }}
        run: |
          # empty string that stays empty if there are no redirects to suggest
          redirect_html=""

          for renamed_redirect in "${RENAMED_REDIRECTS[@]}"; do
            redirect_html+="<li>[&lt;v&gt;-*]: $renamed_redirect</li>"
          done

          for deleted_redirect in "${DELETED_REDIRECTS[@]}"; do
            redirect_html+="<li>[&lt;v&gt;-*]: $deleted_redirect</li>"
          done

          echo "redirect_html=${redirect_html}" >> "$GITHUB_OUTPUT"

      - name: Update PR Description
        if: steps.build-redirect-html.outputs.redirect_html
        uses: MongoCaleb/pr-description-action@4bdfe35b98f64532b419ad20b350a92546cd3aa1
        env:
          REDIRECT_HTML: ${{ steps.build-redirect-html.outputs.redirect_html }}
        with:
          regex: "- \\[ \\] Did you add redirects\\?.*"
          appendContentOnMatchOnly: false
          regexFlags: is
          content: "- [ ] Did you add redirects?\n *Suggested redirects for moved/deleted files (replace &lt;v&gt; with earliest backport target version):*\n${{ steps.build-redirect-html.outputs.redirect_html }}\n"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for duplicates in redirects file
        run: |
          # Specify the file to check  
          file="$REDIRECTS_FILE"

          if [[ -f "$file" ]]; then  
            duplicates=$(sort "$file" | uniq -d)  
            if [[ -n "$duplicates" ]]; then  
              echo "Duplicate lines found in $file:"  
              echo "$duplicates"  
              exit 1 # error
            fi
          else  
            echo "File $file does not exist. Skipping duplicate check."  
          fi