name: Add Redirects
on:
  pull_request_target:
jobs:
  add-redirects:
    name: Get Redirects for Modified Files
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@c65cd883420fd2eb864698a825fc4162dd94482c
        with:
          include_all_old_new_renamed_files: true
      - name: Make Redirects for Renamed Files
        id: renamed-files
        if: steps.changed-files.outputs.renamed_files_count > 0
        env:
          RENAMED_FILES: ${{ steps.changed-files.outputs.all_old_new_renamed_files }}
        run: |
          renamed_redirects=""
          for file in $RENAMED_FILES; do
            if [[ ! "$file" == *.txt ]]; then
              continue
            fi
            old=$(echo "$file" | cut -d',' -f1)
            old="${old#source}"
            old="${old%.txt}"
            new=$(echo "$file" | cut -d',' -f2)
            new="${new#source}"
            new="${new%.txt}"
            #single quotes = ${var} rendered literally; double quotes = $var interpreted
            renamed_redirects+='<li>[&lt;v&gt;-*]: ${prefix}/${version}'"$old"'/ -> ${base}/${version}'"$new"'/</li>'
          done
          echo "redirects=${renamed_redirects}" >> "$GITHUB_OUTPUT"
      - name: Make Redirects for Deleted Files
        id: deleted-files
        if: steps.changed-files.outputs.deleted_files_count > 0
        env:
          DELETED_FILES: ${{ steps.changed-files.outputs.deleted_files }}
        run: |
          deleted_redirects=""
          for file in $DELETED_FILES; do
            if [[ ! "$file" == *.txt ]]; then
              continue
            fi
            old=$(echo "$file" | cut -d',' -f1)
            old="${old#source}"
            old="${old%.txt}"
            deleted_redirects+='<li>[&lt;v&gt;-*]: ${prefix}/${version}'"$old"'/ -> ${base}/${version}/</li>'
          done
          echo "redirects=${deleted_redirects}" >> "$GITHUB_OUTPUT"
      - name: Update PR Description
        if: steps.changed-files.outputs.renamed_files_count > 0 || steps.changed-files.outputs.deleted_files_count > 0
        uses: MongoCaleb/pr-description-action@4bdfe35b98f64532b419ad20b350a92546cd3aa1
        with:
          regex: "- \\[ \\] Did you add redirects\\?.*"
          appendContentOnMatchOnly: false
          regexFlags: is
          content: "- [ ] Did you add redirects?\n *Suggested redirects for moved/deleted files (replace &lt;v&gt; with earliest backport target version):*\n${{ steps.renamed-files.outputs.redirects }}${{ steps.deleted-files.outputs.redirects }}\n"
          token: ${{ secrets.GITHUB_TOKEN }}