name: add-redirects
on:
  pull_request:
    paths:
      - "source/**"
jobs:
  get-redirects-renamed:
    name: Get Renamed Files
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - name: Get renamed files
        id: changed-files
        # pin to a specific commit to ensure stability
        uses: tj-actions/changed-files@c65cd883420fd2eb864698a825fc4162dd94482c
        with:
          files: |
            *.txt
          include_all_old_new_renamed_files: true
          write_output_files: true
      - name: Debug renamed files output
        id: output-renamed
        env:
          RENAMED_FILES: ${{ steps.changed_files.outputs.all_old_new_renamed_files_count }}
        run: |
          echo "Renamed files count: $RENAMED_FILES" 
      - name: Write renamed files to output
        id: write-renamed
        run: |
          printf "%s\n" "$RENAMED_FILES" > .github/outputs/renamed_files.txt
      - name: Verify the contents of renamed_files.txt
        run: |
          cat .github/outputs/renamed_files.txt